language: python
cache: pip
# py37+ is not supported on trusty.
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-401959085
dist: xenial
sudo: true
python:
  - 3.6
  - 3.7
  - 3.8-dev
  - nightly
env:
  - FFMPEG_VERSION=release
  - FFMPEG_VERSION=git
matrix:
  allow_failures:
    - python: 3.8-dev
    - python: nightly
before_install:
  - scripts/install-ffmpeg-on-travis
  - export PATH=$PWD/bin:$PATH
install:
  - pip install '.[dev]' tox-travis
script:
  - make qa
  - make tests
